name: fire_x_bloc
description: FireXBloc wraps FirebaseAuth with Bloc, offering a simplified and efficient solution for managing authentication in your apps.
version: 1.1.0+13
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  equatable: ^2.0.5
  
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  firebase_auth_mocks: ^0.14.1
  import_sorter: ^4.6.0
  mockito: ^5.4.4
  very_good_analysis: ^6.0.0

import_sorter:
  emojis: false
  comments: false
